### ISSUE TITLE
Support for laravel 8?

### ISSUE THREAD

**Issue by truesteps** [mozammil/laravel-message-interceptor#2]
Hey man! Could you update the laravel package version in `composer.json` ? Maybe test out if it works with laravel 8 but from what i've read in the documentation it should :). I would love to use this package. Thanks!!!

**Comment by mozammil** [comment]
@truesteps I just tagged `v1.2.0` that should add support for Laravel 8. Let me know if you encounter any issues.

Thanks to @ppshobi for making this PR.
